#!/bin/sh
#
###############################################################################
# sd-agent
#
# Written by Boxed Ice <hello@boxedice.com>
# A server monitoring daemon for www.serverdensity.com
#
# Licensed under Simplified BSD License (see LICENSE)
#
###############################################################################
#
# chkconfig: 345 85 15
# description: Server Density Monitoring Agent

### BEGIN INIT INFO
# Provides: sd-agent
# Short-Description: Start and start sd-agent
# Description: sd-agent is the monitoring agent component for Server Density
### END INIT INFO

AGENTPATH="/usr/bin/sd-agent/agent.py"

[ -f $AGENTPATH ] || echo "/usr/bin/sd-agent not found"

# Source function library.
if [ -f /etc/init.d/functions ]; then
        . /etc/init.d/functions
fi

if [ -f /etc/SuSE-release ]; then
        . /etc/rc.status
        rc_reset
fi

# Action to take
case "$1" in
  start)
        python $AGENTPATH stop init
        python $AGENTPATH start init --clean
        if [ -f /etc/SuSE-release ]; then
                rc_status -v
        elif [ -f /etc/debian_version ] || [ -f /etc/lsb-release ] || [ -f /etc/gentoo-release ]; then
                echo " Started"
        else
            	success
                echo
        fi
        echo
	;;
  stop)
       	python $AGENTPATH stop init
       	
        if [ -f /etc/SuSE-release ]; then
                rc_status -v
        elif [ -f /etc/debian_version ] || [ -f /etc/lsb-release ] || [ -f /etc/gentoo-release ]; then
                echo " Stopped"
        else
                success
                echo
        fi
        echo
	;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
    	echo "Usage: /etc/init.d/sd-agent start|stop|restart"
        exit 1
esac

exit 0