#!/bin/sh

### BEGIN INIT INFO
# Provides: dd-agent
# Short-Description: Start and start dd-agent
# Description: dd-agent is the monitoring agent component for Datadog
# Required-Start: $remote_fs
# Required-Stop: $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

set -e

. /lib/lsb/init-functions

AGENTPATH="/usr/bin/dd-agent"
AGENTUSER="dd-agent"
AGENTCONF="/etc/dd-agent/datadog.conf"
USE_SUPERVISOR="/usr/bin/dd-forwarder"
PIDPATH="/var/run/dd-agent"
NAME="dd-agent"
DESC="datadog agent"

[ -x $AGENTPATH ] || echo "$AGENTPATH not found"

# Action to take
case "$1" in
  start)
        if [ ! -f $AGENTCONF ]; then
            echo "$AGENTCONF not found. Exiting"
            exit 0;
        fi
        echo -n "Starting $DESC: "


        if [ -f $USE_SUPERVISOR ]; then
            echo -n "(using supervisorctl) "
            supervisorctl start datadog-agent:*
        else
            if [ ! -f $PIDPATH ]; then
                mkdir -p $PIDPATH
            fi
            chown $AGENTUSER $PIDPATH
            su $AGENTUSER -c "$AGENTPATH start init --clean"
        fi
        echo "$NAME."
    ;;
  stop)
        if [ ! -f $AGENTCONF ]; then
            echo "$AGENTCONF not found. Exiting"
            exit 0;
        fi

        echo -n "Stopping $DESC: "
        if [ -f $USE_SUPERVISOR ]; then
            echo -n "(using supervisorctl) "
            supervisorctl stop datadog-agent:*
        else
            $AGENTPATH stop init
        fi

        echo "$NAME."
    ;;
  restart|force-reload)
        $0 stop
        $0 start
    ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart}"
        exit 1
    ;;
esac

exit 0
