#! /bin/bash

set -e

case "$1" in
    configure)
        update-rc.d datadog-agent defaults
        adduser --system dd-agent --shell /bin/sh --no-create-home --quiet
        chown -R dd-agent /etc/dd-agent

        # Update the supervisor process group to ensure it has the proper
        # configuration when we restart the datadog-agent.
        echo "Reading supervisor configuration."
        supervisorctl reread || echo "Error reading supervisor configuration. Please restart supervisor."

        echo "Updating supervisor configuration."
        sleep 8     # FIXME mattp: Supervisor seems to need this time.
        supervisorctl update || echo "Error updating supervisor configuration. Please restart supervisor."

        if which invoke-rc.d >/dev/null 2>&1; then
            invoke-rc.d datadog-agent restart
        else
            /etc/init.d/datadog-agent restart
        fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
    ;;
esac

#DEBHELPER#

exit 0
