#! /bin/bash

set -e

case "$1" in
    configure)
        update-rc.d datadog-agent defaults
        adduser --system dd-agent --shell /bin/sh --no-create-home --quiet
        chown root:root /etc/init.d/datadog-agent
        chown -R dd-agent:root /etc/dd-agent
        chown -R dd-agent:root /var/log/datadog
        chown -R root:root /usr/share/datadog
        chown -h root:root /usr/bin/dogstatsd
        chown -h root:root /usr/bin/dd-agent
        chown -h root:root /usr/bin/dd-forwarder

        # Since we call this script from install_agent.sh, we don't want to
        # start the agent here. We need install_agent.sh to update datadog.conf before
        # the agent will start successfully, which is done after this script is
        # run.
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
    ;;
esac

#DEBHELPER#

exit 0
