#! /bin/bash
set -e

if [ "$1" = purge ]; then
    update-rc.d datadog-agent remove
fi

supervisorctl reread || echo "Error rereading supervisor config in postrm"
supervisorctl update || echo "Error updating supervisor in postrm"

exit 0
