#! /bin/bash
set -e

if [ -f /etc/init.d/datadog-agent ]; then
    if which invoke-rc.d >/dev/null 2>&1; then
        invoke-rc.d datadog-agent stop || true
    else
        /etc/init.d/datadog-agent stop || true
    fi
fi

# Since we now package our own supervisor config, we no longer want
# the old config to be loaded. Since supervisor automatically loads
# configs in conf.d, we have to delete the old config file.
if [ -f /etc/supervisor/conf.d/ddagent.conf ]; then
    echo "Removing old configuration from system supervisord"
    rm /etc/supervisor/conf.d/ddagent.conf
fi

# Previous versions of dd-agent created this file but didn't do
# anything with it.
if [ -f /etc/dd-agent/supervisor_ddagent.conf ]; then
    echo "Removing unused supervisor config file"
    rm /etc/dd-agent/supervisor_ddagent.conf
fi

#DEBHELPER#
exit 0
