#! /bin/bash
set -e
suprunning=$(pgrep -fl supervisord)

if [[ -z $suprunning ]]; then
    echo "[postrm] Starting supervisor"
    service supervisor start
fi
  
supervisorctl reread
supervisorctl update

if which invoke-rc.d >/dev/null 2>&1; then
    invoke-rc.d datadog-agent start
else
    /etc/init.d/datadog-agent start
fi

exit 0
