#! /bin/sh

set -e 

case "$1" in
    configure)
	suprunning=$(pgrep -fl supervisord)
	if [ -z "$suprunning" ]; then
	    echo "Restarting supervisord"
	    service supervisor start
	fi
        supervisorctl reread
        supervisorctl update

        if which invoke-rc.d >/dev/null 2>&1; then
            invoke-rc.d datadog-agent restart
        else
            /etc/init.d/datadog-agent restart
        fi
    ;;
    *)
    ;;
esac

#DEBHELPER#

exit 0
