#! /bin/sh

set -e 

if [ -f /etc/init.d/datadog-agent ]; then
    if which invoke-rc.d >/dev/null 2>&1; then
        invoke-rc.d datadog-agent stop
    else
        /etc/init.d/datadog-agent stop
    fi
fi

mkdir -p /var/log
touch /var/log/dogstatsd.log
chown dd-agent:dd-agent /var/log/dogstatsd.log

#DEBHELPER#

exit 0
