#!/bin/sh

### BEGIN INIT INFO
# Provides: dd-agent
# Short-Description: Start and start dd-agent
# Description: dd-agent is the monitoring agent component for Datadog
# Required-Start: $remote_fs
# Required-Stop: $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

set -e

. /lib/lsb/init-functions

AGENTPATH="/usr/bin/dd-agent"
AGENTUSER="dd-agent"
PIDPATH="/var/run/sd-agent"
NAME="dd-agent"
DESC="datadog agent"

[ -x $AGENTPATH ] || echo "$AGENTPATH not found"

# Action to take
case "$1" in
  start)
        echo -n "Starting $DESC: "
        if [ ! -f $PIDPATH ]; then
            mkdir -p $PIDPATH
        fi
        chown $AGENTUSER $PIDPATH
        su $AGENTUSER -c "$AGENTPATH start init --clean"
        echo "$NAME."
    ;;
  stop)
        echo -n "Stopping $DESC: "
        $AGENTPATH stop init
        echo "$NAME."
    ;;
  restart|force-reload)
        $0 stop
        $0 start
    ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart}"
        exit 1
    ;;
esac

exit 0
