#!/bin/bash

# Relative cd to where this script resides
# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd $THIS_DIR/..
source venv/bin/activate
python agent/agent.py info
python agent/dogstatsd.py info
python agent/ddagent.py info
popd
