desc "Runs jshint on all the pup .js files, using the config at .jshintrc in the root directory"
task :hint do
	sh "./node_modules/.bin/jshint ./static/pup.full.js"
end

desc "Runs nodeunit tests located in the test directory"
task :test do
	sh "./node_modules/.bin/nodeunit ./test"
end

desc "Concatinates all the javascript files into ./static/pup.js"
task :js do
	src_dir = "#{pwd}/assets/javascript"
	dest_dir = "#{pwd}/static"

	# ordering matters due to variable scope
	to_sprocketize = [
		"Constants.js",
		"Metric.js",
		"Store.js",
		"PupSocket.js",
		"MetricGraph.js",
		"PupController.js"
	]

	# Figure out why I need dummy.js
	cmd = "sprocketize --directory=#{src_dir} -I dummy.js #{to_sprocketize.join(" ")}"
	sh "#{cmd} > #{dest_dir}/pup.full.js"
	sh "#{cmd} | uglifyjs > #{dest_dir}/pup.js"
end

desc "Compiles CSS files into ./static/pup.css"
task :css do
	# Compile here
end

desc "Start the Pup Tornado server"
task :start do
	sh "python pup.py"
end


desc "Compile assets and run"
task :run_all => [:js, :css, :start]
